import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { CheckCircle2, Eye, FileUp, IndianRupee, Search, Stamp, Upload, XCircle } from 'lucide-react';
import { api, documentUrl } from '../api/client.js';
import ApplicationTable from '../components/ApplicationTable.jsx';
import Badge from '../components/Badge.jsx';
import Modal from '../components/Modal.jsx';
import StatCard from '../components/StatCard.jsx';
import { officialDocumentPdf } from '../utils/pdf.js';
import { rupees, shortDate } from '../utils/format.js';

export default function AdminDashboard() {
  const [applications, setApplications] = useState([]);
  const [stats, setStats] = useState(null);
  const [config, setConfig] = useState(null);
  const [filters, setFilters] = useState({ search: '', department: '', documentType: '', status: '' });
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState(null);
  const [bundle, setBundle] = useState(null);
  const [remarks, setRemarks] = useState('');
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    api.config().then(setConfig);
  }, []);

  useEffect(() => {
    load();
  }, [filters.department, filters.documentType, filters.status]);

  async function load(extra = filters) {
    setLoading(true);
    try {
      const [appData, statData] = await Promise.all([api.listApplications(extra), api.stats()]);
      setApplications(appData.applications);
      setStats(statData.stats);
    } catch (error) {
      toast.error(error.message);
    } finally {
      setLoading(false);
    }
  }

  async function openApplication(app) {
    setSelected(app);
    setRemarks(app.admin_remarks || '');
    const data = await api.getApplication(app.id);
    setBundle(data);
  }

  async function changeStatus(status) {
    if (!selected) return;
    setSaving(true);
    try {
      const data = await api.updateApplication(selected.id, { status, admin_remarks: remarks });
      toast.success(`Application ${status.replace('_', ' ')}.`);
      setSelected(data.application);
      const refreshed = await api.getApplication(selected.id);
      setBundle(refreshed);
      await load();
    } catch (error) {
      toast.error(error.message);
    } finally {
      setSaving(false);
    }
  }

  async function uploadFile(file) {
    if (!file || !selected) return;
    setSaving(true);
    try {
      await api.uploadDocument(selected.id, 'approved', file, file.name);
      const data = await api.updateApplication(selected.id, { status: 'approved', admin_remarks: remarks || 'Document uploaded and approved.' });
      toast.success('PDF uploaded and request approved.');
      setSelected(data.application);
      setBundle(await api.getApplication(selected.id));
      await load();
    } catch (error) {
      toast.error(error.message);
    } finally {
      setSaving(false);
    }
  }

  async function generateDocument() {
    if (!selected) return;
    setSaving(true);
    try {
      const blob = officialDocumentPdf(selected);
      await api.uploadDocument(selected.id, 'approved', blob, `${selected.id}-${selected.document_type}.pdf`);
      const data = await api.updateApplication(selected.id, {
        status: 'approved',
        admin_remarks: remarks || 'Document generated by academic office and approved.'
      });
      toast.success('Document generated and approved.');
      setSelected(data.application);
      setBundle(await api.getApplication(selected.id));
      await load();
    } catch (error) {
      toast.error(error.message);
    } finally {
      setSaving(false);
    }
  }

  function searchSubmit(event) {
    event.preventDefault();
    load(filters);
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="text-lg font-bold text-slate-900">Admin Office Dashboard</h2>
          <p className="text-sm text-slate-500">Review paid student applications and issue verified PDFs.</p>
        </div>
        {loading ? <span className="text-sm text-slate-500">Loading records...</span> : null}
      </div>

      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Total Requests" value={stats?.totalApplications ?? 0} />
        <StatCard label="Pending Requests" value={stats?.pending ?? 0} tone="pending" />
        <StatCard label="Approved Requests" value={stats?.approved ?? 0} tone="approved" />
        <StatCard label="Revenue Collected" value={rupees(stats?.revenue ?? 0)} icon={IndianRupee} />
      </div>

      <section className="erp-card p-4">
        <form onSubmit={searchSubmit} className="mb-4 grid gap-3 lg:grid-cols-[1.4fr_1fr_1fr_1fr_auto]">
          <label className="relative">
            <span className="mb-1 block text-xs font-semibold uppercase text-slate-500">Search</span>
            <Search className="pointer-events-none absolute bottom-2.5 left-2.5 h-4 w-4 text-slate-400" />
            <input
              className="form-input pl-8"
              placeholder="Register number, student name, or application ID"
              value={filters.search}
              onChange={(event) => setFilters({ ...filters, search: event.target.value })}
            />
          </label>
          <Filter label="Department" value={filters.department} options={config?.metadata?.departments || []} onChange={(value) => setFilters({ ...filters, department: value })} />
          <Filter label="Document Type" value={filters.documentType} options={config?.metadata?.documentTypes || []} onChange={(value) => setFilters({ ...filters, documentType: value })} />
          <Filter label="Status" value={filters.status} options={['under_review', 'approved', 'rejected']} onChange={(value) => setFilters({ ...filters, status: value })} />
          <div className="flex items-end">
            <button className="btn-primary px-4 py-2 text-sm font-semibold">Apply</button>
          </div>
        </form>

        <ApplicationTable
          applications={applications}
          actions={(app) => (
            <button className="btn-secondary inline-flex items-center gap-2 px-3 py-1.5 text-xs font-semibold" onClick={() => openApplication(app)}>
              <Eye className="h-4 w-4" />
              View
            </button>
          )}
        />
      </section>

      {selected ? (
        <Modal title={`Application Review - ${selected.id}`} onClose={() => { setSelected(null); setBundle(null); }}>
          <div className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr]">
            <section className="border border-slate-200 p-3">
              <div className="mb-3 flex items-center justify-between">
                <h3 className="font-bold text-slate-900">Student Details</h3>
                <Badge value={selected.status} />
              </div>
              <dl className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm">
                <Detail label="Name" value={selected.full_name} />
                <Detail label="Register No." value={selected.register_number} />
                <Detail label="Department" value={selected.department} />
                <Detail label="Year" value={selected.year} />
                <Detail label="Document" value={selected.document_type} />
                <Detail label="Amount" value={rupees(selected.amount)} />
                <Detail label="Applied" value={shortDate(selected.created_at)} />
                <Detail label="Payment" value={selected.payment_status} />
              </dl>
              <div className="mt-3 border-t border-slate-200 pt-3 text-sm">
                <div className="font-semibold text-slate-700">Purpose</div>
                <p className="mt-1 text-slate-600">{selected.purpose}</p>
                {selected.additional_notes ? <p className="mt-2 text-slate-500">{selected.additional_notes}</p> : null}
              </div>
            </section>

            <section className="border border-slate-200 p-3">
              <h3 className="mb-3 font-bold text-slate-900">Office Action</h3>
              <label className="block">
                <span className="mb-1 block text-sm font-semibold text-slate-700">Admin Remarks</span>
                <textarea className="form-input min-h-24" value={remarks} onChange={(event) => setRemarks(event.target.value)} />
              </label>
              <div className="mt-3 grid gap-2 sm:grid-cols-2">
                <button className="btn-success flex items-center justify-center gap-2 px-3 py-2 text-sm font-semibold" onClick={() => changeStatus('approved')} disabled={saving}>
                  <CheckCircle2 className="h-4 w-4" />
                  Approve
                </button>
                <button className="btn-danger flex items-center justify-center gap-2 px-3 py-2 text-sm font-semibold" onClick={() => changeStatus('rejected')} disabled={saving}>
                  <XCircle className="h-4 w-4" />
                  Reject
                </button>
                <button className="btn-primary flex items-center justify-center gap-2 px-3 py-2 text-sm font-semibold sm:col-span-2" onClick={generateDocument} disabled={saving}>
                  <Stamp className="h-4 w-4" />
                  Generate Document
                </button>
                <label className="btn-secondary flex cursor-pointer items-center justify-center gap-2 px-3 py-2 text-sm font-semibold sm:col-span-2">
                  <Upload className="h-4 w-4" />
                  Upload PDF
                  <input className="hidden" type="file" accept="application/pdf" onChange={(event) => uploadFile(event.target.files?.[0])} />
                </label>
              </div>
            </section>
          </div>

          <section className="mt-4 border border-slate-200 p-3">
            <h3 className="mb-2 flex items-center gap-2 font-bold text-slate-900">
              <FileUp className="h-4 w-4" />
              Uploaded Documents
            </h3>
            <div className="grid gap-2">
              {(bundle?.documents || []).map((doc) => (
                <a key={doc.id} className="flex items-center justify-between border border-slate-200 px-3 py-2 text-sm hover:bg-slate-50" href={documentUrl(doc.file_url)} target="_blank" rel="noreferrer">
                  <span>{doc.file_name}</span>
                  <span className="text-xs font-semibold uppercase text-slate-500">{doc.type}</span>
                </a>
              ))}
              {!(bundle?.documents || []).length ? <div className="text-sm text-slate-500">No PDF uploaded for this request yet.</div> : null}
            </div>
          </section>
        </Modal>
      ) : null}
    </div>
  );
}

function Filter({ label, value, options, onChange }) {
  return (
    <label>
      <span className="mb-1 block text-xs font-semibold uppercase text-slate-500">{label}</span>
      <select className="form-input" value={value} onChange={(event) => onChange(event.target.value)}>
        <option value="">All</option>
        {options.map((option) => <option key={option} value={option}>{option.replace(/_/g, ' ')}</option>)}
      </select>
    </label>
  );
}

function Detail({ label, value }) {
  return (
    <div>
      <dt className="text-xs font-semibold uppercase text-slate-500">{label}</dt>
      <dd className="mt-0.5 font-medium text-slate-900">{value || '-'}</dd>
    </div>
  );
}
